app.py
from flask import Flask
from flask_jwt_extended import JWTManager
from routes import route_blueprint, initialize_database

app = Flask(__name__)
app.secret_key = 'test'
app.config['JWT_SECRET_KEY'] = 'super-secret'
jwt = JWTManager(app)

app.register_blueprint(route_blueprint)

@app.route('/init_db', methods=['GET'])
def init_db_route():
    return initialize_database()

if __name__ == '__main__':
    app.run(debug=True, port=5005)

routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, session
from flask_jwt_extended import jwt_required
from auth_utils import login_user, register_user
from client_utils import list_clients_utils, client_utils
from aps_utils import wifi_ap_utils, list_aps_utils
from dashboard import dashboard_utils, home_utils
from db_utils import init_db, get_client_movement

route_blueprint = Blueprint('route', __name__)

def initialize_database():
    try:
        init_db()
        return jsonify({"msg": "Database initialized"}), 200
    except mysql.connector.Error as err:
        return jsonify({'error': str(err)}), 500

@route_blueprint.before_request
def add_jwt_token_to_headers():
    access_token = session.get('access_token')
    if access_token and 'Authorization' not in request.headers:
        new_headers = request.headers.to_wsgi_list()
        new_headers.append(('Authorization', f"Bearer {access_token}"))
        request.environ['HTTP_AUTHORIZATION'] = f"Bearer {access_token}"

@route_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        return login_user()
    return render_template('login.html')

@route_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        return register_user()
    return render_template('register.html')

@route_blueprint.route('/logout', methods=['POST'])
def logout():
    session.pop('username', None)  
    session.pop('access_token', None)
    return redirect(url_for('route.login'))

@route_blueprint.route('/')
def home():
    return home_utils()

@route_blueprint.route('/dashboard')
@jwt_required()
def dashboard():
    return dashboard_utils()

@route_blueprint.route('/wifi_ap/<int:ap_id>')
@jwt_required()
def wifi_ap(ap_id):
    return wifi_ap_utils(ap_id)

@route_blueprint.route('/client/<int:client_id>')
@jwt_required()
def client(client_id):
    return client_utils(client_id)

@route_blueprint.route('/list_aps')
@jwt_required()
def list_aps():
    return list_aps_utils()

@route_blueprint.route('/list_clients')
@jwt_required()
def list_clients():
    return list_clients_utils()

@route_blueprint.route('/client/<int:client_id>/movement_history')
@jwt_required()
def client_movement_history(client_id):
    movements = get_client_movement(client_id)
    return render_template('client_movement_history.html', movements=movements)

templates/client.html
<!DOCTYPE html>
<html>
<head>
    <title>Informations sur le Client</title>
</head>
<body>
    <h1>Informations sur le Client</h1>
    <p>Adresse MAC : {{ client_info[0] }}</p>
    <p>Nom d'hôte : {{ client_info[1] }}</p>
    <p>Appareil : {{ client_info[2] }}</p>
    <p>Type de système d'exploitation : {{ client_info[3] }}</p>
    <p>Durée totale de connexion : {{ client_info[4] }} secondes</p>
    <p>Bornes connectées : {{ client_info[5] }}</p>
    <p>Volume de données envoyées : {{ client_info[6] }} bytes</p>
    <p>Volume de données reçues : {{ client_info[7] }} bytes</p>
    <a href="{{ url_for('route.list_clients') }}">Retour au Clients</a>
    <a href="{{ url_for('route.dashboard') }}">Retour au Dashboard</a>
</body>
</html>

templates/client_movement_history.html
<!DOCTYPE html>
<html>
<head>
    <title>Historique de déplacement du client</title>
</head>
<body>
    <h1>Historique de déplacement du client</h1>
    <ul>
        {% for movement in movements %}
            <li>Connecté à {{ movement[0] }} le {{ movement[1] }}</li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('route.list_clients') }}">Retour au Clients</a>
    <a href="{{ url_for('route.dashboard') }}">Retour au Dashboard</a>
</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
</head>
<body>
    <h1>Dashboard de {{ username }}</h1>
    <p>Nombre de bornes : {{ total_aps }}</p>
    <a href="{{ url_for('route.list_aps') }}">Lister les bornes WiFi</a><br>
    <p>Nombre de clients : {{ total_clients }}</p>
    <a href="{{ url_for('route.list_clients') }}">Lister les clients</a>
    <p>Volume total upstream échangé : {{ total_volume_upstream }} bytes</p>
    <p>Volume total downstream échangé : {{ total_volume_downstream }} bytes</p>
    <p>Volume total échangé : {{ total_volume }} bytes</p>
    <form action="/logout" method="post">
        <button type="submit">Déconnexion</button>
    </form>
</body>
</html>

templates/list_aps.html
<!DOCTYPE html>
<html>
<head>
    <title>Liste des Bornes WiFi</title>
</head>
<body>
    <h1>Liste des Bornes WiFi</h1>
    <ul>
        {% for ap in aps %}
            <li><a href="{{ url_for('route.wifi_ap', ap_id=ap[0]) }}">{{ ap[1] }}</a></li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('route.dashboard') }}">Retour au Dashboard</a>
</body>
</html>

templates/list_clients.html
<!DOCTYPE html>
<html>
<head>
    <title>Liste des Clients</title>
</head>
<body>
    <h1>Liste des Clients</h1>
    <ul>
        {% for client in clients %}
            <li>
                <a href="{{ url_for('route.client', client_id=client[0]) }}">{{ client[1] }} - {{ client[2] }}</a> 
                (<a href="{{ url_for('route.client_movement_history', client_id=client[0]) }}">Voir l'historique de déplacement</a>)
            </li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('route.dashboard') }}">Retour au Dashboard</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion</title>
</head>
<body>
    <h2>Connexion</h2>
    <form action="/login" method="post">
        <label for="username">Nom d'utilisateur :</label><br>
        <input type="text" id="username" name="username"><br>
        <label for="password">Mot de passe :</label><br>
        <input type="password" id="password" name="password"><br><br>
        <input type="submit" value="Connexion">
    </form>
    <a href="{{ url_for('route.register') }}">Retour à l'inscription</a>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
</head>
<body>
    <h2>Inscription</h2>
    <form action="/register" method="post">
        <label for="username">Nom d'utilisateur :</label><br>
        <input type="text" id="username" name="username"><br>
        <label for="password">Mot de passe :</label><br>
        <input type="password" id="password" name="password"><br><br>
        <input type="submit" value="S'inscrire">
    </form>
    <a href="{{ url_for('route.login') }}">Retour à la connexion</a>
</body>
</html>

templates/wifi_ap.html
<!DOCTYPE html>
<html>
<head>
    <title>Informations sur la Borne WiFi</title>
</head>
<body>
    <h1>Informations sur la Borne WiFi</h1>
    <p>Nom : {{ ap_info[0] }}</p>
    <p>Volume de données envoyées : {{ ap_info[1] }} bytes</p>
    <p>Volume de données reçues : {{ ap_info[2] }} bytes</p>
    <a href="{{ url_for('route.list_aps') }}">Retour au Borne</a>
    <a href="{{ url_for('route.dashboard') }}">Retour au Dashboard</a>
</body>
</html>